<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SwfTools' => array($vendorDir . '/swftools/swftools/src'),
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src'),
    'Skyzyx\\Components\\Mimetypes' => array($vendorDir . '/skyzyx/mimetypes/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Neutron' => array($vendorDir . '/neutron/temporary-filesystem/src'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'FFMpeg' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Aws' => array($vendorDir . '/aws/aws-sdk-php/src'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
